name: CI - Verificação de Código PHP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-php:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Executar Lint nos arquivos PHP
        run: |
          find . -type f -name "*.php" -exec php -l {} \;
